str = ''
str += '<div id="header">'
str += ''
str += '	<ul class="tab">'
str += '		<li><a href="index.html">LMS 발송</a></li>'
str += '		<li class="on"><a href="02_list.html">인력 관리</a></li>'
str += '		<li><a href="03.html">발송 이력</a></li>'
str += '		<li><a href="04.html">관리자 계정</a></li>'
str += '	</ul>'
str += ''
str += '	<a href="login.html" class="btn_sml log"><span>로그아웃</span></a>'
str += ''
str += '</div>'

document.write(str);